version: '3.3'

services:
  mssql:
    image: mcr.microsoft.com/mssql/server:2022-latest
    container_name: sqlserver2022
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: "StrongPassword123!"
    ports:
      - "1433:1433"
    volumes:
      - mssql_data:/var/opt/mssql
      - ./backup:/var/opt/mssql/backup   # локальная папка с .bak файлами

  mssql-tools:
    image: mcr.microsoft.com/mssql-tools
    container_name: sqlserver-tools
    depends_on:
      - mssql
    stdin_open: true
    tty: true
    # пробрасываем ту же сеть, чтобы sqlcmd видел сервер
    network_mode: "host"
    volumes:
      - ./backup:/var/opt/mssql/backup

volumes:
  mssql_data:
